# 1.How to get the common items between two python numpy arrays?
* Q. Get the common items between a and b

* Input:

* a = np.array([1,2,3,2,3,4,3,4,5,6])

* b = np.array([7,2,10,2,7,4,9,4,9,8])

In [13]:
import numpy as np


# create 2 arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Display the arrays
print("Original arrays", a, ' ', b)

# use the np.intersect1d method
c = np.intersect1d(a, b)
c


Original arrays [1 2 3 2 3 4 3 4 5 6]   [ 7  2 10  2  7  4  9  4  9  8]


array([2, 4])

# 2. How to remove from one array those items that exist in another?
* Q. From array a remove all items present in array b

* Input:

* a = np.array([1,2,3,4,5])

* b = np.array([5,6,7,8,9])

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a, b)
c

array([1, 2, 3, 4])

# 3.How to get the positions where elements of two arrays match?
* Q. Get the positions where elements of a and b match

* Input:

* a = np.array([1,2,3,2,3,4,3,4,5,6])

* b = np.array([7,2,10,2,7,4,9,4,9,8])

In [14]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

# 4.How to extract all numbers between a given range from a numpy array?
* Q. Get all items between 5 and 10 from a.

* Input:

* a = np.array([2, 6, 1, 9, 10, 3, 27])

In [15]:
import numpy as np
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

# 5.How to make a python function that handles scalars to work on numpy arrays?
* Q. Convert the function maxx that works on two scalars, to work on two arrays.

* Input:

* def maxx(x, y): """Get the maximum of two items""" if x >= y:

*  return x
*else:

  return y
* maxx(1, 5) #> 5

In [16]:
import numpy as np
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

# 6. How to swap two columns in a 2d numpy array?
* Q. Swap columns 1 and 2 in the array arr.

* arr = np.arange(9).reshape(3,3)

* arr

* Show Solution

* Input

* arr = np.arange(9).reshape(3,3)
* arr

In [17]:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# 7.How to swap two rows in a 2d numpy array?
* Q. Swap rows 1 and 2 in the array arr:

* arr = np.arange(9).reshape(3,3)

* arr

* Show Solution

* Input

* arr = np.arange(9).reshape(3,3)


In [18]:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 8. How to reverse the rows of a 2D array?
* Q. Reverse the rows of a 2D array arr.

* Input

* arr = np.arange(9).reshape(3,3)

* Show Solution

* Input

* arr = np.arange(9).reshape(3,3)

In [19]:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# 9. How to reverse the columns of a 2D array?
* Q. Reverse the columns of a 2D array arr.

* Input

* arr = np.arange(9).reshape(3,3)

* Show Solution

* Input

* arr = np.arange(9).reshape(3,3)

In [20]:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# 10. How to create a 2D array containing random floats between 5 and 10?
* Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
* Show Solution

* Input

* arr = np.arange(9).reshape(3,3)

In [24]:
import numpy as np
arr = np.arange(9).reshape(3,3)

rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

[[9.45742468 6.49421482 7.57751705]
 [5.65812457 7.41732307 7.85294962]
 [8.58243526 8.65320298 7.51732265]
 [7.8540053  9.9690283  6.79065491]
 [8.75569496 8.76704034 7.27474386]]
