In [20]:
# 1.How to convert a float (32 bits) array into an integer (32 bits) in place
import numpy as np
k = np.arange(10, dtype=np.int32)
k = Z.astype(np.float32, copy=False)
print(k)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [22]:
# Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [17]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [7]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [12]:
# Create a 10x10x10 array with random values
import numpy as np
arr = np.random.randint(10,size=(10,10,10))
arr

array([[[0, 5, 6, 6, 1, 3, 0, 2, 2, 9],
        [0, 0, 6, 6, 8, 0, 8, 4, 9, 4],
        [6, 8, 9, 3, 9, 0, 1, 2, 2, 8],
        [7, 5, 4, 9, 8, 6, 9, 3, 6, 3],
        [2, 0, 8, 0, 6, 9, 6, 5, 0, 8],
        [0, 2, 6, 8, 4, 9, 1, 1, 0, 4],
        [0, 9, 1, 2, 8, 1, 0, 9, 3, 3],
        [4, 9, 3, 6, 8, 3, 2, 9, 5, 5],
        [7, 8, 9, 4, 5, 1, 1, 8, 7, 7],
        [3, 8, 9, 5, 7, 8, 5, 8, 6, 7]],

       [[8, 3, 5, 4, 8, 1, 6, 3, 5, 0],
        [4, 3, 2, 2, 5, 4, 2, 4, 9, 9],
        [1, 4, 7, 6, 5, 2, 4, 9, 9, 8],
        [9, 8, 5, 0, 0, 9, 6, 6, 4, 4],
        [3, 3, 5, 7, 7, 1, 4, 8, 6, 7],
        [9, 3, 7, 8, 7, 6, 4, 7, 7, 9],
        [6, 3, 8, 3, 9, 6, 4, 6, 5, 8],
        [3, 7, 9, 1, 7, 2, 8, 4, 0, 9],
        [4, 5, 3, 6, 5, 9, 3, 8, 4, 2],
        [7, 5, 5, 6, 1, 0, 5, 0, 7, 8]],

       [[1, 9, 3, 7, 2, 2, 4, 8, 7, 9],
        [7, 4, 6, 0, 6, 3, 8, 5, 1, 1],
        [7, 9, 3, 2, 2, 6, 0, 2, 6, 1],
        [0, 0, 9, 7, 8, 7, 6, 9, 0, 6],
        [9, 6, 7, 6, 5, 7, 1, 3, 7, 

In [13]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [15]:
# Create a 10x10 array with random values and find the minimum and maximum values
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.6084953  0.47386201 0.24430588 0.66179936 0.31628181 0.54822407
  0.08692082 0.38573276 0.38368002 0.09487503]
 [0.41314725 0.28971342 0.94703695 0.71213001 0.95990396 0.02887633
  0.34034692 0.90992144 0.45703378 0.50911651]
 [0.85514971 0.64804619 0.38202819 0.23520197 0.82816629 0.57153646
  0.53173755 0.58661198 0.3739457  0.1421709 ]
 [0.80379044 0.33136762 0.13298669 0.08045969 0.31169883 0.56365512
  0.76564256 0.08653908 0.9436529  0.8642103 ]
 [0.54940717 0.09355229 0.44100325 0.57390041 0.99505426 0.32097517
  0.86317493 0.83960571 0.37012773 0.02771373]
 [0.56556269 0.28005807 0.01804009 0.09113544 0.83704153 0.51973726
  0.06885418 0.29836992 0.68718097 0.63579196]
 [0.31159638 0.97571875 0.22144751 0.16392307 0.24568936 0.28151375
  0.63887753 0.79488058 0.25773418 0.33722897]
 [0.60641444 0.10056419 0.08435215 0.03652865 0.75723346 0.21594768
  0.18049996 0.32162179 0.75091549 0.73974095]
 [0.98358267 0.79235137 0.86047019 0.78803573 0.26823255 0.36914

In [13]:
# Create a 10x10 matrix with row values ranging from 0 to 9
import numpy as np
x = np.zeros((10,10))
print("Original array:")
print(x)
print("Row values ranging from 0 to 9.")
x += np.arange(10)
print(x)


Original array:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Row values ranging from 0 to 9.
[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


In [18]:
# Consider two random matrices A anb B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [19]:
# Create a random vector of size 1000 and find the mean value

Z = np.random.random(1000)
m = Z.mean()
print (m)

0.48590440686811953


In [20]:
# Create random vector of size 100 and replace the maximum value by 0
import numpy as np
x = np.random.random(1000)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)


Original array:
[6.82961633e-01 4.03813300e-01 7.56783206e-01 8.72582176e-01
 9.30144797e-01 1.99016572e-01 1.53407739e-01 4.03115775e-01
 1.27182029e-01 9.96716924e-01 1.86300356e-01 5.05879804e-01
 5.12566237e-01 8.56129120e-01 2.99442007e-01 1.44614021e-01
 7.60011569e-01 5.34705126e-02 3.86642628e-01 4.89736305e-01
 6.30191029e-01 4.72504141e-02 6.66759199e-01 9.27121112e-01
 5.20873387e-01 1.83420129e-01 8.01044984e-01 2.73164918e-01
 8.69930580e-01 2.41707438e-01 3.18644994e-02 1.72009694e-01
 2.17813166e-01 4.13037538e-01 5.74054809e-01 2.59068502e-01
 4.95594298e-01 1.47013982e-01 9.01448712e-01 1.34571175e-02
 9.66902209e-01 9.73632847e-02 8.06114411e-01 3.30016852e-02
 1.21710049e-01 7.89241325e-01 3.77524389e-01 9.99622917e-01
 7.64888429e-01 7.00237240e-01 6.47511277e-01 5.12669520e-01
 1.89839697e-01 5.49452682e-01 7.74493743e-01 4.83808452e-01
 1.63782660e-01 4.37633485e-01 7.73230692e-01 4.22361855e-01
 2.47775703e-01 8.39108003e-01 8.30752676e-01 6.66113131e-02
 4.03980

In [22]:
# Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
import numpy

print("Creating 5X2 array using numpy.arange")
sampleArray = numpy.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [6]:
#Following is the provided numPy array. 
#Return array of items by taking the third column from all rows
#sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of items in the third column from all rows is")
newArray = sampleArray[...,2]
print(newArray)

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows is
[33 66 99]


In [7]:
#Return array of odd rows and even columns from below numpy array
#sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of odd rows and even columns")
new_Array = sampleArray[::2, 1::2]
print(new_Array)

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


In [8]:
#Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
##arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
###arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

resultArray  = arrayOne + arrayTwo
print("addition of two arrays is \n")
print(resultArray)

for num in np.nditer(resultArray, op_flags = ['readwrite']):
   num[...] = num*num
print("\nResult array after calculating the square root of all elements\n")
print(resultArray)

addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]


In [9]:
##Split the array into four equal-sized sub-arrays
##Note: Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
Array = np.arange(10, 34, 1)
Array = Array.reshape(8,3)
print (Array)

print("\nDividing 8X3 array into 4 sub array\n")
subArrays = np.split(Array, 4) 
print(subArrays)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [10]:
#Sort following NumPy array
##Case 1: Sort array by the second row
###Case 2: Sort the array by the second column
####sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

sort_Array_ByRow = sampleArray[:,sampleArray[1,:].argsort()]
print("Sorting Original array by secoond row")
print(sort_Array_ByRow)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]


In [11]:
#Print max from axis 0 and min from axis 1 from the following 2-D array.
##sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

min_OfAxisOne = np.amin(sampleArray, 1) 
print("Printing min Of Axis 1")
print(min_OfAxisOne)

max_OfAxisOne = np.amax(sampleArray, 0) 
print("Printing max Of Axis 0")
print(max_OfAxisOne)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing min Of Axis 1
[34 12 53]
Printing max Of Axis 0
[82 94 73]


In [12]:
#Delete the second column from a given array and insert the following new column in its place.
# sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
# newColumn = numpy.array([[10,10,10]])
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [27]:
 # Create two 2-D arrays and Plot them using matplotlib
import numpy as np
import matplotlib as ml
import matplotlib.pyplot as plt
a = random.choice([1,2,3,4,5],size =(3,5))
print(a)

[[3 4 2 5 3]
 [5 1 1 4 2]
 [2 5 5 5 3]]
