In [6]:
#1.How to extract items that satisfy a given condition from 1D array?
#Q. Extract all odd numbers from arr

#Input:

#arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [7]:
#2.How to replace items that satisfy a condition with another value in numpy array?

#Q. Replace all odd numbers in arr with -1

#Input:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [12]:
#3.How to replace items that satisfy a condition without affecting the original array?

#Q. Replace all odd numbers in arr with -1 without changing arr

#Input:

#arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
#4.How to reshape an array?

#Q. Convert a 1D array to a 2D array with 2 rows

#Input:

#np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
#5.How to stack two arrays vertically?

#Q. Stack arrays a and b vertically

#Input

#a = np.arange(10).reshape(2,-1)
#b = np.repeat(1, 10).reshape(2,-1)
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
#6.How to stack two arrays horizontally?

#Q. Stack the arrays a and b horizontally.

#Input

#a = np.arange(10).reshape(2,-1)

#b = np.repeat(1, 10).reshape(2,-1)
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [19]:
#7.How to generate custom sequences in numpy without hardcoding?

#Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

#Input:
#a = np.array([1,2,3])
import numpy as np
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
#8.How to get the common items between two python numpy arrays?

#Q. Get the common items between a and b

#Input:

#a = np.array([1,2,3,2,3,4,3,4,5,6])
#b = np.array([7,2,10,2,7,4,9,4,9,8])
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

In [44]:
#9.How to remove from one array those items that exist in another?

#Q. From array a remove all items present in array b

#Input:

#a = np.array([1,2,3,4,5])
#b = np.array([5,6,7,8,9])
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [24]:
#10.How to get the positions where elements of two arrays match?
#Q. Get the positions where elements of a and b match

#Input:

#a = np.array([1,2,3,2,3,4,3,4,5,6])
#b = np.array([7,2,10,2,7,4,9,4,9,8])
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [43]:
#11.How to extract all numbers between a given range from a numpy array?

#Q. Get all items between 5 and 10 from a.

#Input:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
#12.How to make a python function that handles scalars to work on numpy arrays?
#Q. Convert the function maxx that works on two scalars, to work on two arrays.

#Input:
#def maxx(x, y):
 #   """Get the maximum of two items"""
  #  if x >= y:
  #      return x
  #  else:
  #      return y

#maxx(1, 5)
#> 5
import numpy as np
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., ..., 9., 7., 5.])

In [41]:
#13.How to swap two columns in a 2d numpy array?

#Q. Swap columns 1 and 2 in the array arr.

#arr = np.arange(9).reshape(3,3)
#arr
import numpy as np
arr = np.arange(9).reshape(3,3)
arr
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [40]:
#14.How to swap two rows in a 2d numpy array?
#Q. Swap rows 1 and 2 in the array arr:

#arr = np.arange(9).reshape(3,3)
#arr
import numpy as np
arr = np.arange(9).reshape(3,3)

arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [39]:
#15.How to reverse the rows of a 2D array?

#Q. Reverse the rows of a 2D array arr.

# Input
#arr = np.arange(9).reshape(3,3)
import numpy as np 
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [30]:
#16.How to reverse the columns of a 2D array?

#Q. Reverse the columns of a 2D array arr.

# Input
#arr = np.arange(9).reshape(3,3)
import numpy as np
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [38]:
#17.How to create a 2D array containing random floats between 5 and 10?

#Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Input
import numpy as np
arr = np.arange(9).reshape(3,3)
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

[[5.632 9.699 8.642]
 [9.92  7.299 5.569]
 [8.179 6.533 7.647]
 [8.142 9.581 9.479]
 [6.386 8.44  9.405]]


In [33]:
#18.How to print only 3 decimal places in python numpy array?

#Q. Print or show only 3 decimal places of the numpy array rand_arr.

#Input:

#rand_arr = np.random.random((5,3))
import numpy as np
rand_arr = np.random.random((5,3))

# Create the random array
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision=3)
rand_arr[:4]



array([[0.654, 0.12 , 0.602],
       [0.686, 0.75 , 0.782],
       [0.307, 0.127, 0.532],
       [0.016, 0.656, 0.576]])

In [37]:
#19.How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

#Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

#Input:

# Create the random array
#np.random.seed(100)
#rand_arr = np.random.random([3,3])/1e3
#rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]]
# Reset printoptions to default
import numpy as np
np.set_printoptions(suppress=False)

# Create the random array
import numpy as np
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [36]:
#20.How to limit the number of items printed in output of numpy array?

#Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.
#Input:

#a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
import numpy as np
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])